library/book/urls.py
from django.urls import path
from . import views


app_name = "book"


urlpatterns = [
    path("", views.books_page, name="book_main_page"),
    path("<int:book_id>/", views.book_detail, name="book_detail"),
    path("add_book/", views.add_book, name="add_book"),
    path("book_add_page/", views.book_add_page, name="book_add_page"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from authentication.views import HomePageView

from api.v1.author_api.views import AuthorViewSet
from api.v1.auth_api.views import UserViewSet

from api.v1.book_api.views import BookApiList, BookRetrieveApiList, BookApiCreate
from api.v1.order_api.views import OrderViewSet, OrderUserViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"author", AuthorViewSet)
router.register(r"user", UserViewSet)
router.register(r"order", OrderViewSet)
router.register(r"user/(?P<user_id>\d+)/order", OrderUserViewSet)


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
    path("api/v1/", include(router.urls)),
    path("api/v1/book/", BookApiList.as_view(), name="book_list"),
    path("api/v1/book/<int:pk>/", BookRetrieveApiList.as_view(), name="book_ret"),
    path("api/v1/book/create/", BookApiCreate.as_view(), name="create"),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
]

library/book/models.py
from django.db import models
from author.models import Author


class Book(models.Model):
    """
    This class represents an Book. \n
    Attributes:
    -----------
    param name: Describes name of the book
    type name: str max_length=128
    param description: Describes description of the book
    type description: str
    param count: Describes count of the book
    type count: int default=10
    param authors: list of Authors
    type authors: list->Author
    """

    id = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, max_length=128)
    description = models.CharField(blank=True, max_length=256)
    count = models.IntegerField(default=10)
    authors = models.ManyToManyField(Author)
    year_of_publication = models.IntegerField(null=True, blank=True)
    date_of_issue = models.DateField(null=True, blank=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return f"id: {self.id} --- {self.name} --- count: {self.count} "

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f"Book(id={self.id})"

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        return Book.objects.get(id=book_id) if Book.objects.filter(id=book_id) else None

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Book.get_by_id(book_id) is None:
            return False
        Book.objects.get(id=book_id).delete()
        return True

    @staticmethod
    def create(name, description, count=10, authors=[]):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        if len(name) > 128:
            return None

        book = Book()
        book.name = name
        book.description = description
        book.count = count
        book.save()
        if isinstance(authors, list):
            for elem in authors:
                book.authors.add(elem)
        else:
            book.authors = [].append(authors)
        book.save()
        return book


    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """
        return {
            "id": self.id,
            "name": f"{self.name}",
            "description": f"{self.description}",
            "count": f"{self.count}",
            "authors": f"{self.authors}",
        }

    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """
        if name is not None:
            self.name = name

        if description is not None:
            self.description = description

        if count is not None:
            self.count = count

        if self.count < 0:
            self.count = 0

        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        if authors is not None:
            for elem in authors:
                self.authors.add(elem)
                self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for elem in self.authors.values():
            self.authors.remove(elem["id"])

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        return list(Book.objects.all())

library/book/forms.py
from django import forms
from .models import Book
from authentication.models import CustomUser
from author.models import Author


class AddFormBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-input",
                    "placeholder": "Enter Name",
                    "class": "form-control",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "cols": 30,
                    "rows": 2,
                    "placeholder": "Write a description",
                    "class": "form-control",
                }
            ),
            "count": forms.NumberInput(attrs={"class": "form-control", "default": 10}),
            "authors": forms.SelectMultiple(attrs={"size": 3, "class": "form-control"}),
            "year_of_publication": forms.Select(
                choices=[(year, year) for year in range(1900, 2024)],
                attrs={"class": "form-control"}
            ),
            "date_of_issue": forms.DateInput(
                attrs={"class": "form-control", "type": "date"}
            ),
        }


class FilterForm(forms.Form):
    parameter = forms.ChoiceField(
        choices=[
            ("None", "All books"),
            ("authors", "Authors ID"),
            ("title", "Title"),
            ("count", "Count"),
        ],
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
    )
    value = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}), required=False
    )


class AddUserForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.all().order_by("id"),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
        empty_label=None,
        to_field_name="id",
    )


class AddAuthorForm(forms.Form):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        label="Choose an author",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

library/book/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Book
from .models import Author
from authentication.models import CustomUser
from order.models import Order
from django.utils.datastructures import MultiValueDictKeyError
from .forms import AddFormBook, FilterForm, AddUserForm, AddAuthorForm


@login_required
def books_page(request):
    filter_form = FilterForm(request.POST or None)
    add_user_form = AddUserForm(request.POST or None)
    add_book_form = AddFormBook(request.POST or None)

    if filter_form.is_valid():
        parameter = filter_form.cleaned_data["parameter"]
        value = filter_form.cleaned_data["value"]

        if parameter == "None" or not value:
            books = Book.objects.all()
        elif parameter == "authors":
            books = Book.objects.filter(authors=value)
        elif parameter == "title":
            books = Book.objects.filter(name=value)
        elif parameter == "count":
            books = Book.objects.filter(count=value)
    else:
        books = Book.objects.all()

    return render(
        request,
        template_name="book/basik.html",
        context={
            "books": books,
            "filter_form": filter_form,
            "add_user_form": add_user_form,
            "add_book_form": add_book_form,
            "user": CustomUser.objects.all(),
        },
    )


def book_add_page(request):
    filter_form = FilterForm(request.POST or None)
    add_user_form = AddUserForm(request.POST or None)
    add_book_form = AddFormBook(request.POST or None)
    user = CustomUser.objects.all
    book = Book.objects.all()
    try:
        if request.POST["user"]:
            all_order = Order.objects.all()
            book = []
            for elem in all_order:
                if elem.user.id == int(request.POST["user"]):
                    book.append(elem.book)
    except MultiValueDictKeyError:
        book = Book.objects.all()
    return render(
        request,
        template_name="book/basik.html",
        context={
            "books": book,
            "user": user,
            "filter_form": filter_form,
            "add_user_form": add_user_form,
            "add_book_form": add_book_form,
        },
    )


@login_required
def book_detail(request, book_id):
    authors = Author.objects.all()
    book = Book.objects.get(id=book_id)
    book_authors = book.authors.all()

    if request.method == "POST":
        form = AddAuthorForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data["author"]
            book.authors.add(author)
            book.save()
    else:
        form = AddAuthorForm()
    return render(
        request,
        template_name="book/book.html",
        context={
            "book": Book.get_by_id(book_id),
            "authors": authors,
            "book_authors": book_authors,
            "form": form,
        },
    )


def add_book(request):
    if request.method == "POST":
        form = AddFormBook(request.POST)
        if form.is_valid():
            form.save()
            return books_page(request)
        else:
            print(form.errors)
    else:
        form = AddFormBook()
    return render(
        request,
        template_name="book/add_book.html",
        context={"form": form, "authors": Author.objects.all()},
    )

library/book/templates/book/add_book.html
{% extends 'base.html' %}
{% block title %}Add book{% endblock %}
{% block content %}
<body>
  <div class="p-3 --bs-info-text-emphasis ">
<h2>New book:</h2>
{% if request.user.role == 1 %}
<form method="post" action="{% url 'book:add_book' %}">
  {% csrf_token %}{{ form.non_field_errors }}
  <div class="mb-2">
    <label class="col-form-label">{{form.name.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3">
        {{form.name}}{{form.name.errors}}
      </div>
    </div>
  </div>
  <div class="mb-2">
    <label class="col-form-label">{{form.description.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3"> 
        {{form.description}} {{form.description.errors}}
      </div>
    </div>
  </div>
  <div class="mb-2">
    <label class="col-form-label">{{form.count.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3"> 
        {{form.count}}
      </div>
    </div>
  </div>
  <div class="mb-2">
    <label class="col-form-label">{{form.authors.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3">
        {{form.authors}}
      </div>
    </div>
  </div>
  <div class="mb-2">
    <label class="col-form-label">{{form.year_of_publication.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3">
        {{form.year_of_publication}} {{form.year_of_publication.errors}}
      </div>
    </div>
  </div>
  <div class="mb-2">
    <label class="col-form-label">{{form.date_of_issue.label_tag}}</label>
    <div class="d-flex">
      <div class="col-sm-3">
        {{form.date_of_issue}}{{form.date_of_issue.errors}}
      </div>
    </div>
  </div>
  <div class="mb-2">
  <button type="submit" class="btn btn-success">Create</button>
  </div>
</form>
{% endif %}
</div>
</body>
</html>
{% endblock %}

library/book/templates/book/basik.html
{% extends 'base.html' %}
{% block title %}Books list{% endblock %}
{% block content %}
<body>
  <div class="p-3 --bs-info-text-emphasis ">
<div class="mb-3">
  <form class="row g-3" action="{% url 'book:book_main_page' %}", method = "post", target = "_self">
    {% csrf_token %}
    {{filter_form.value.errors}}
    <div class="col-auto">
      <label >{{filter_form.parameter.label_tag}}</label>
    </div>
    <div class="col-auto">
      <div class="col-sm-12">{{filter_form.parameter}}</div>
    </div>
    <div class="col-auto">
      <div class="col-sm-12">{{filter_form.value}}</div>
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary mb-3">Filter</button>
    </div>
  </form>
  </div>
{% if request.user.role == 1 %}
<div class="mb-3">
<form class="row g-3" action="{% url 'book:book_add_page' %}", method = "post", target = "_self">
  {% csrf_token %}
  {{add_user_form.value.errors}}
  <div class="col-auto">
    <label >{{add_user_form.user.label_tag}}</label>
  </div>
  <div class="col-auto">
    <div class="col-sm-12">{{add_user_form.user}}</div>
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-3">Filter</button>
  </div>
</form>
</div>
{% endif %}

{% if request.user.role == 1 %}
    <form action="{% url 'book:add_book' %}", method = "post">
    {% csrf_token %}
      <button type="submit" class="btn btn-success mb-3" >New book</button>
    </form>
{% endif %}
<ul>
  {% for x in books %}
    <li><a href="/book/{{ x.id }}">{{ x.name}}</a></li>
  {% endfor %}
</ul>
</div>
</body>
</html>
{% endblock %}

library/book/templates/book/book.html
{% extends 'base.html' %}
{% block title %}Book{% endblock %}
{% block content %}
<body>
  <div class="p-3 --bs-info-text-emphasis ">
<h2>Information about book:</h2>
<ul class="list-group list-group-flush">
  <li class="list-group-item">Name: {{book.name}}</li>
  <li class="list-group-item">Author: {% for elem in book_authors %}
    {{elem.name}} {{elem.surname}} {{elem.patronymic}},
    {% endfor %} </li>
  <li class="list-group-item">Count: {{book.count}}</li>
  <li class="list-group-item">Descriptions:{{book.description}}</li>
</ul>

{% if request.user.role == 1 %}
  <form action="{% url 'book:book_detail' book.id %}" method="post">
    {% csrf_token %}
    <div class="mb-2">
      <label class="col-form-label">Add author:</label>
      <div class="d-flex">
        <div class="col-sm-3">
          {{form.author}}
        </div>
      </div>
    </div>
    <div class="mb-2">
    <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
{% endif %}
  </div>
</body>
</html>
{% endblock %}

library/book/templates/book/user_books.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Books</title>
  </head>
  <body>
    <p><a href="/home/out"> Log out</a></p>
    <p><a href="/home"> Home </a></p>
    {% if user != None %}
      <h1>Information about User id = {{user_id}} books:</h1>

      {% if books %}

        {% for book in books %}
        <p> - Title: {{book.name}} Description: {{book.description}}</p>
        {% endfor %}
      {%  else %}
      <p> User doesn't have any books</p>
      {% endif %}
    {% else %}
    <h1>No User</h1>
    {% endif %}

  </body>
</html>

library/book/templates/book/users.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Choose User</title>
  </head>
  <body>
    <p><a href="/home/out"> Log out</a></p>
    <p><a href="/home"> Home </a></p>
    <h1>Information about user's books:</h1>
    <h2>Find user</h2>
    <ul>
      {% for user in users %}
      <li>
        User id: - {{ user.id }} -
        <a href="{% url 'book:user_books' user.id %}"> List of books </a>
      </li>
      {% empty %}
      <li>No user yet.</li>
      {% endfor %}
    </ul>
  </body>
</html>