library/book/urls.py
from django.urls import path
from . import views


app_name = "book"


urlpatterns = [
    path("", views.books_page, name="book_main_page"),
    path("<int:book_id>/", views.book_detail, name="book_detail"),
    path("add_book/", views.add_book, name="add_book"),
    path("book_add_page/", views.book_add_page, name="book_add_page"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from authentication.views import HomePageView

from api.v1.author_api.views import AuthorViewSet
from api.v1.auth_api.views import UserViewSet

from api.v1.book_api.views import BookApiList, BookRetrieveApiList, BookApiCreate
from api.v1.order_api.views import OrderViewSet, OrderUserViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"author", AuthorViewSet)
router.register(r"user", UserViewSet)
router.register(r"order", OrderViewSet)
router.register(r"user/(?P<user_id>\d+)/order", OrderUserViewSet)


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
    path("api/v1/", include(router.urls)),
    path("api/v1/book/", BookApiList.as_view(), name="book_list"),
    path("api/v1/book/<int:pk>/", BookRetrieveApiList.as_view(), name="book_ret"),
    path("api/v1/book/create/", BookApiCreate.as_view(), name="create"),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
]

library/order/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian


app_name = "order"

urlpatterns = [
    path("", views.order_list, name="order"),
    path("create/", views.create_order, name="create_order"),
    path("user/", (views.user_orders), name="user_orders"),
    path(
        "close/<int:order_id>/",
        deny_non_librarian(views.close_order),
        name="close_order",
    ),
]

library/order/models.py
from django.db import models, DataError

from authentication.models import CustomUser
from book.models import Book


class Order(models.Model):
    """
    This class represents an Order.
    """

    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField(default=None, null=True, blank=True)
    plated_end_at = models.DateTimeField(default=None)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        """
        if self.end_at == None:
            return (
                f"id: {self.pk}"
                f"--- {self.user.first_name} {self.user.last_name} ---"
                f" {self.book.name}"
            )
        else:
            return (
                f"'id': {self.pk}, "
                f"'user': CustomUser(id={self.user.pk}),"
                f" 'book': Book(id={self.book.pk}),"
                f" 'created_at': '{self.created_at}',"
                f" 'end_at': '{self.end_at}',"
                f" 'plated_end_at': '{self.plated_end_at}'"
            )

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        """
        return f"{self.__class__.__name__}(id={self.id})"

    def to_dict(self):
        """
        :return: order id, book id, user id, order created_at, order end_at, order plated_end_at
        """
        return {
            "id": self.id,
            "book": self.book.id,
            "self": self.user.id,
            "created_at": self.created_at,
            "end_at": self.end_at,
            "plated_end_at": self.plated_end_at,
        }

    @staticmethod
    def create(user, book, plated_end_at):
        orders = Order.objects.all()
        books = set()
        for order in orders:
            if not order.end_at:
                books.add(order.book.id)
        if book.id in books and book.count == 1:
            return None
        try:
            order = Order(user=user, book=book, plated_end_at=plated_end_at)
            order.save()
            return order
        except ValueError:
            return None
        except DataError:
            return None

    @staticmethod
    def get_by_id(order_id):
        try:
            return Order.objects.get(pk=order_id)
        except Order.DoesNotExist:
            return None

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at:
            self.plated_end_at = plated_end_at
        if end_at:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        list_order = list(Order.objects.all())
        return list_order

    @staticmethod
    def get_not_returned_books():
        orders = Order.objects.filter(end_at=None)
        orders_list = list(orders)
        return orders_list

    @staticmethod
    def delete_by_id(order_id):
        try:
            a = Order.objects.get(pk=order_id)
            a.delete()
            return True
        except Order.DoesNotExist:
            return False

library/order/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    plated_end_at = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control"})
    )

    class Meta:
        model = Order
        fields = ["book", "plated_end_at"]
        widgets = {
            "book": forms.Select(attrs={"class": "form-control"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        book = cleaned_data.get("book")
        if book and book.count < 1:
            raise forms.ValidationError("No book available, you can't order this book.")
        return cleaned_data

    def save_order(self, user):
        order = self.save(commit=False)
        order.user = user
        book = self.cleaned_data["book"]
        book.count -= 1
        book.save()
        order.save()
        return order

library/order/views.py
from .models import Order
from book.models import Book
from django.shortcuts import render, redirect
from datetime import datetime
from django.contrib import messages
from .forms import OrderForm
from django.core.exceptions import ValidationError


def order_list(request):
    orders = Order.objects.order_by("user__id")
    return render(request, "order/order.html", {"orders": orders})


def user_orders(request):
    current_user = request.user
    orders = Order.objects.filter(user=current_user)
    return render(request, "order/user_orders.html", {"orders": orders})


def create_order(request):
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save_order(request.user)
            messages.success(request, "Order placed!")
        else: 
            print(form.errors)
    else:
        form = OrderForm()

    return render(request, "order/create_order.html", {"form": form})


def close_order(request, order_id):
    order = Order.get_by_id(order_id)
    book = Book.objects.get(name=order.book.name)

    if order:
        order.update(end_at=datetime.now())
        book.count += 1
        book.save()

    return redirect("order:order")

library/order/templates/order/create_order.html
{% extends 'base.html' %}
{% block title %}Create order{% endblock %}
{% block content %}
<body>
  <div class="p-3 --bs-info-text-emphasis ">
    <div class="mb-3">
      {% if request.user.is_superuser %}
    <a class="button me-md-4" href="{% url 'order:order' %}">  All orders </a>
    {% endif %}
    <a class="button me-md-4" href="{% url 'order:create_order' %}"> Create order</a>
    <a class="button me-md-4" href="{% url 'order:user_orders' %}"> My orders </a>
    </div>


  <h2>Create Order:</h2>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <form method="POST">
    {% csrf_token %}
    <div class="mb-2">
    {{ form.non_field_errors }}
  </div>
    <div class="mb-2">
      <label class="col-form-label">{{form.book.label_tag}}</label>
      <div class="d-flex">
        <div class="col-sm-3">
          {{form.book}}{{form.book.errors}}
        </div>
      </div>
    </div>
    <div class="mb-2">
      <label class="col-form-label">{{form.plated_end_at.label_tag}}</label>
      <div class="d-flex">
        <div class="col-sm-3"> 
          {{form.plated_end_at}} {{form.plated_end_at.errors}}
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-success">Create Order</button>
  </form>
  </div>
</body>
</html>
{% endblock %}

library/order/templates/order/order.html
{% extends 'base.html' %}

{% block title %}order{% endblock %}
{% block content %}
<div class="p-3 --bs-info-text-emphasis ">

{% if request.user.is_superuser %}
<div class="mb-3">
<a class="button me-md-4" href="{% url 'order:order' %}">  All orders </a>
{% endif %}
<a class="button me-md-4" href="{% url 'order:create_order' %}"> Create order</a>
<a class="button me-md-4" href="{% url 'order:user_orders' %}"> My orders </a>
</div>
{% if request.user.is_superuser %}
<h2>All Orders:</h2>
<ul>
{% for order in orders %}
    <li>
        <p>User: {{ order.user.first_name }} - {{ order.user.last_name }} - {{ order.user.middle_name }} - id:{{ order.user.id }} </p> 
        <p>Book: {{ order.book.name }} </p>
            <p>Order created at : {{ order.created_at }} </p> 
                <p>Order plated end at: {{ order.plated_end_at }}</p> 
        {% if not order.end_at %}
        <form action="{% url 'order:close_order' order.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success" >Close Order</button>
        </form>
        {% else %}
        <p>--- Order end at: -{{ order.end_at }} ---</p>
        {% endif %}
        <br>
{% empty %}
    <li>No orders yet.</li>
{% endfor %}
{% endif %}
    </div>
{% endblock %}

library/order/templates/order/user_orders.html
{% extends 'base.html' %}
{% block title %}user order{% endblock %}

{% block content %}

<div class="p-3 --bs-info-text-emphasis">
    <div class="mb-3">

    {% if request.user.is_superuser %}

<a class="button me-md-4" href="{% url 'order:order' %}">  All orders </a>
{% endif %}
<a class="button me-md-4" href="{% url 'order:create_order' %}"> Create order</a>
<a class="button me-md-4" href="{% url 'order:user_orders' %}"> My orders </a>
    </div>

        <h2>My Orders:</h2>
        <ul>

        {% for order in orders %}
            <li>
                <p>Book: {{ order.book.name }} </p>
                    <p>Order created at : {{ order.created_at }} </p> 
                        <p>Order plated end at: {{ order.plated_end_at }}</p> 
                        <p>Order end at: -{{ order.end_at }}-</p> 
        {% empty %}
            <li>No orders yet.</li>
        {% endfor %}
        </div>
{% endblock %}