library/authentication/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian


app_name = "authentication"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="index"),
    path("register/", views.registration, name="registration"),
    path("authentication/", views.user_page, name="user_page"),
    path("out/", views.out, name="log_out"),
    path("users/", deny_non_librarian(views.users_page), name="all_users"),
    path(
        "user/<int:user_id>",
        deny_non_librarian(views.user_details),
        name="special_user",
    ),
]

library/author/urls.py
from django.urls import path
from . import views
from library.functions import deny_non_librarian


app_name = 'author'

urlpatterns = [
    path("", deny_non_librarian(views.AuthorPage.as_view()), name='author'),
    path("<int:pk>", deny_non_librarian(views.AuthorDetails.as_view()), name='details'),
    path("<int:author_id>/remove", deny_non_librarian(views.remove_author), name='remove_author'),
    path("new/", deny_non_librarian(views.add_author), name='add_author'),
]

library/book/urls.py
from django.urls import path
from . import views


app_name = "book"


urlpatterns = [
    path("", views.books_page, name="book_main_page"),
    path("<int:book_id>/", views.book_detail, name="book_detail"),
    path("add_book/", views.add_book, name="add_book"),
    path("book_add_page/", views.book_add_page, name="book_add_page"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from authentication.views import HomePageView

from api.v1.author_api.views import AuthorViewSet
from api.v1.auth_api.views import UserViewSet

from api.v1.book_api.views import BookApiList, BookRetrieveApiList, BookApiCreate
from api.v1.order_api.views import OrderViewSet, OrderUserViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"author", AuthorViewSet)
router.register(r"user", UserViewSet)
router.register(r"order", OrderViewSet)
router.register(r"user/(?P<user_id>\d+)/order", OrderUserViewSet)


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
    path("api/v1/", include(router.urls)),
    path("api/v1/book/", BookApiList.as_view(), name="book_list"),
    path("api/v1/book/<int:pk>/", BookRetrieveApiList.as_view(), name="book_ret"),
    path("api/v1/book/create/", BookApiCreate.as_view(), name="create"),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
]

library/order/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian


app_name = "order"

urlpatterns = [
    path("", views.order_list, name="order"),
    path("create/", views.create_order, name="create_order"),
    path("user/", (views.user_orders), name="user_orders"),
    path(
        "close/<int:order_id>/",
        deny_non_librarian(views.close_order),
        name="close_order",
    ),
]

library/authentication/models.py
import datetime

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models

ROLE_CHOICES = (
    (0, "visitor"),
    (1, "librarian"),
)


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, role, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(("The Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.role = int(role)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("role", 1)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    This class represents a basic user.
    """

    first_name = models.CharField(max_length=20, default=None, null=True)
    last_name = models.CharField(max_length=20, default=None, null=True)
    middle_name = models.CharField(max_length=20, default=None, null=True)
    email = models.CharField(max_length=100, unique=True, default=None)
    password = models.CharField(default=None, max_length=255)
    created_at = models.DateTimeField(editable=False, auto_now=datetime.datetime.now())
    updated_at = models.DateTimeField(auto_now=datetime.datetime.now())
    role = models.IntegerField(choices=ROLE_CHOICES, default=0)
    is_active = models.BooleanField(default=True)
    id = models.AutoField(primary_key=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    objects = CustomUserManager()

    def __str__(self):
        """
        Magic method is redefined to show all information about CustomUser.
        """
        return f"Id: {self.id} --- {self.first_name}  {self.middle_name} {self.last_name} --- Role: {self.role}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of CustomUser object.
        """
        return f"{CustomUser.__name__}(id={self.id})"

    @staticmethod
    def get_by_id(user_id):
        """
        Returns user by id
        """
        custom_user = CustomUser.objects.filter(id=user_id).first()
        return custom_user if custom_user else None

    @staticmethod
    def get_by_email(email):
        """
        Returns user by email
        """
        custom_user = CustomUser.objects.filter(email=email).first()
        return custom_user if custom_user else None

    @staticmethod
    def delete_by_id(user_id):
        """
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        user_to_delete = CustomUser.objects.filter(id=user_id).first()
        if user_to_delete:
            CustomUser.objects.filter(id=user_id).delete()
            return True
        return False

    @staticmethod
    def create(email, password, first_name=None, middle_name=None, last_name=None):
        """ """
        if (
            len(first_name) <= 20
            and len(middle_name) <= 20
            and len(last_name) <= 20
            and len(email) <= 100
            and len(email.split("@")) == 2
            and len(CustomUser.objects.filter(email=email)) == 0
        ):
            custom_user = CustomUser(
                email=email,
                password=password,
                first_name=first_name,
                middle_name=middle_name,
                last_name=last_name,
            )
            custom_user.save()
            return custom_user
        return None

    def to_dict(self):
        """
        :return: user id, user first_name, user middle_name, user last_name,
                 user email, user password, user updated_at, user created_at, user is_active
        """
        return {
            "id": self.id,
            "first_name": f"{self.first_name}",
            "middle_name": f"{self.middle_name}",
            "last_name": f"{self.last_name}",
            "email": f"{self.email}",
            "created_at": int(self.created_at.timestamp()),
            "updated_at": int(self.updated_at.timestamp()),
            "role": self.role,
            "is_active": self.is_active,
        }

    def update(
        self,
        first_name=None,
        last_name=None,
        middle_name=None,
        password=None,
        role=None,
        is_active=None,
    ):
        user_to_update = CustomUser.objects.filter(email=self.email).first()
        if first_name and len(first_name) <= 20:
            user_to_update.first_name = first_name
        if last_name and len(last_name) <= 20:
            user_to_update.last_name = last_name
        if middle_name and len(middle_name) <= 20:
            user_to_update.middle_name = middle_name
        if password:
            user_to_update.password = password
        if role:
            user_to_update.role = role
        if is_active:
            user_to_update.is_active = is_active
        user_to_update.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all users
        """
        return CustomUser.objects.all()

    def get_role_name(self):
        """
        returns str role name
        """
        return ROLE_CHOICES[self.role][1]

library/authentication/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter Email", "required": "True", 'class': 'form-control'}
        ),
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Enter Password", 'class': 'form-control'}
        ),
    )
    
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        if email and password:
            user = authenticate(email=email, password=password)
            if user is None:
                raise ValidationError('Invalid email or password')
        return cleaned_data


class RegisterForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter Email", "required": "True", 'class': 'form-control'}
        ),
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "Enter Password", 'class': 'form-control'}
        ),
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password", 'class': 'form-control'}), label="Confirm Password"
    )
    role = forms.ChoiceField(
        choices=[("0", "Visitor"), ("1", "Librarian")],
        widget=forms.Select(attrs={'class': 'form-select'}),
        )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise ValidationError("Passwords do not match")
        return cleaned_data

library/authentication/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.base import TemplateView
from .models import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.db.utils import IntegrityError
from order.models import Order
from .forms import LoginForm, RegisterForm


class HomePageView(TemplateView):
    template_name = "authentication/index.html"


class RegisterPage(TemplateView):
    template_name = "authentication/register.html"


def user_page(request):
    if request.user.is_authenticated:
        return render(request, template_name="authentication/index.html")
    elif request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(
                request,
                email=form.cleaned_data["email"],
                password=form.cleaned_data["password"],
            )

            if user is not None:
                login(request, user)
                return render(request, template_name="authentication/index.html")
            else:
                return HttpResponse("Error")
    else:
        form = LoginForm()
    return render(request, "authentication/login.html", {"form": form})


def registration(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            role = form.cleaned_data["role"]

            try:
                if role == "0":
                    user = CustomUser.objects.create_user(
                        email=email, password=password, role=role
                    )
                    user.save()
                elif role == "1":
                    user = CustomUser.objects.create_superuser(
                        email=email, password=password, role=role
                    )
                    user.save()
            except IntegrityError:
                return render(
                    request,
                    template_name="authentication/register.html",
                    context={
                        "error_message": "User with that email is already exist, please change email"
                    },
                )
            return redirect("authentication:user_page")
        else:
            return render(
                request,
                template_name="authentication/register.html",
                context={"form": form},
            )
    else:
        form = RegisterForm()
    return render(
        request,
        template_name="authentication/register.html",
        context={"form": form},
    )


def out(request):
    logout(request)
    return redirect("authentication:user_page")


def users_page(request):
    users = CustomUser.objects.order_by("id")
    return render(request, "authentication/all_users.html", {"users": users})


def user_details(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    orders = Order.objects.filter(user_id=user_id)
    return render(
        request, "authentication/user_details.html", {"user": user, "orders": orders}
    )

library/authentication/templates/authentication/all_users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}
{% block content %}
<div class="p-3 --bs-info-text-emphasis ">

    <h2>All Users:</h2>

<table class="table">
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Last Name</th>
        <th scope="col">First Name</th>
        <th scope="col">Middle Name</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Details</th>
    </tr>

    {% for user in users %}
    <tr>       
        <th>{{ user.id }}</th>
        <td>{{user.last_name}}</td>
        <td>{{user.first_name}}</td>
        <td>{{user.middle_name}}</td>
        <td>{{user.email}}</td>
        <td>{{user.get_role_name}}</td>
        <td><a href="{% url 'authentication:special_user' user.id %}">Details</a></td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

library/authentication/templates/authentication/index.html
{% extends 'base.html' %}
{% block title %}Main{% endblock %}
{% block content %}
<br>
<div class="p-3 --bs-info-text-emphasis text-center">
    {% if request.user.is_authenticated %}

        {% if request.user.first_name != None %}
            Hello, {{request.user.first_name}}
        {% else %}
            Hello, User
        {% endif %}
    
        {% endif %}
    </div>

{% endblock %}

library/authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Log in page</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="p-3 --bs-info-text-emphasis text-center">
      <h2>Login to your account</h2>
      <form
        action="{% url 'authentication:user_page' %}"
        method="post"
      >
        {% csrf_token %} {{ form.non_field_errors }}
          <div class="mb-2">
            <label class="col-form-label">Email</label>
            <div class="d-flex justify-content-center">
            <div class="col-sm-3">
              {{form.email}}
              {{form.email.errors}}
            </div>
          </div>
          </div>
          <div class="mb-2">
            <label class="col-form-label">Password</label>
            <div class="d-flex justify-content-center">
              <div class="col-sm-3">
                {{form.password}}
              </div>
          </div>
          </div>
          <div class="mb-3">
            <button type="submit" class="btn btn-success">Log In</button>
          </div>
      </form>
      <p>
        If you haven't an account, please register new one:
        <a href="/home/register"> Register </a>
      </p>
      <p>Return to <a href="{% url 'index' %}"> Main page</a>.</p>
    </div>
  </body>
</html>

library/authentication/templates/authentication/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in page</title>

</head>
<body>
<h1>Login sucsesfully </h1>
<ul>
  {% for x in mymembers %}
    <li>{{ x.email }} {{ x.password }} {{ x.role }}</li>
  {% endfor %}
</ul>
<p> Return to <a href="/home"> Home page</a>.</p>
</body>
</html>

library/authentication/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Registration page</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="p-3 --bs-info-text-emphasis text-center">
      <h2>Create new account</h2>
      {% if error_message %}
      <p>{{ error_message }}</p>
      {% endif %}
      <form action="{% url 'authentication:registration' %}" method="post">
        {% csrf_token %} {{ form.non_field_errors }}
        <div class="mb-2">
          <label class="col-form-label">Email</label>
          <div class="d-flex justify-content-center">
            <div class="col-sm-3">{{form.email}} {{form.email.errors}}</div>
          </div>
        </div>
        <div class="mb-2">
          <label class="col-form-label">Password</label>
          <div class="d-flex justify-content-center">
            <div class="col-sm-3">{{form.password}}</div>
          </div>
        </div>
        <div class="mb-2">
          <label class="col-form-label">Confirm Password</label>
          <div class="d-flex justify-content-center">
            <div class="col-sm-3">{{form.confirm_password}}</div>
          </div>
        </div>
        <div class="mb-2">
          <label class="col-form-label">Role</label>
          <div class="d-flex justify-content-center">
            <div class="col-sm-3">{{form.role}}</div>
          </div>
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-success">REGISTER</button>
        </div>
      </form>

      <p>
        If you already have an account:
        <a href="{% url 'authentication:user_page' %}"> Log in </a>
      </p>
      <p>Return to <a href="{% url 'index' %}"> Home page</a>.</p>
    </div>
  </body>
</html>

library/authentication/templates/authentication/user_details.html
{% extends 'base.html' %}
{% block title %}User_details{% endblock %}
{% block content %}
<div class="p-3 --bs-info-text-emphasis ">
<h2>Informathion about {{user.first_name}} {{user.last_name}}</h2>
<body>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Id: {{user.id}}</li>
        <li class="list-group-item">Role: {% if user.role is 0 %} visitor {% else %} librarian {% endif %}</li>
        <li class="list-group-item">Orders: {{ orders|length }}</li>
        <li class="list-group-item">First_name: {{user.first_name}}</li>
        <li class="list-group-item">Last_name: {{user.last_name}}</li>
        <li class="list-group-item">Middle_name: {{user.middle_name}}</li>
        <li class="list-group-item">Email: {{user.email}}</li>
        <li class="list-group-item">Created_at: {{user.created_at}}</li>
        <li class="list-group-item">Updated_at: {{user.updated_at}}</li>
      </ul>
</body>
</div>
{% endblock %}

library/authentication/templates/authentication/user_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User_page</title>
</head>
<body>
    <H1>Library</H1>
    <br>
    {% if user.is_authenticated %}
    <a class="button" href="/home/out">Log out</a>
    <br>
    <br>
    <a href="{% url 'book:book_main_page' %}"> Books page </a>
    <br>
    {% if request.user.is_superuser %}
    <br>
    <a href="{% url 'author:author' %}"> Authors page </a>
    <br>
    {% endif %}
    <br>
    <a href="{% url 'order:create_order' %}"> Orders page</a>
    {% endif %}
</body>
</html>