library/author/urls.py
from django.urls import path
from . import views
from library.functions import deny_non_librarian


app_name = 'author'

urlpatterns = [
    path("", deny_non_librarian(views.AuthorPage.as_view()), name='author'),
    path("<int:pk>", deny_non_librarian(views.AuthorDetails.as_view()), name='details'),
    path("<int:author_id>/remove", deny_non_librarian(views.remove_author), name='remove_author'),
    path("new/", deny_non_librarian(views.add_author), name='add_author'),
]

library/book/urls.py
from django.urls import path
from . import views


app_name = "book"


urlpatterns = [
    path("", views.books_page, name="book_main_page"),
    path("<int:book_id>/", views.book_detail, name="book_detail"),
    path("add_book/", views.add_book, name="add_book"),
    path("book_add_page/", views.book_add_page, name="book_add_page"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from authentication.views import HomePageView

from api.v1.author_api.views import AuthorViewSet
from api.v1.auth_api.views import UserViewSet

from api.v1.book_api.views import BookApiList, BookRetrieveApiList, BookApiCreate
from api.v1.order_api.views import OrderViewSet, OrderUserViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"author", AuthorViewSet)
router.register(r"user", UserViewSet)
router.register(r"order", OrderViewSet)
router.register(r"user/(?P<user_id>\d+)/order", OrderUserViewSet)


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
    path("api/v1/", include(router.urls)),
    path("api/v1/book/", BookApiList.as_view(), name="book_list"),
    path("api/v1/book/<int:pk>/", BookRetrieveApiList.as_view(), name="book_ret"),
    path("api/v1/book/create/", BookApiCreate.as_view(), name="create"),
    path("api/v1/auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
]

library/author/models.py
from django.db import models


class Author(models.Model):
    """
    This class represents an Author.
    """

    name = models.CharField(blank=True, max_length=20)
    surname = models.CharField(blank=True, max_length=20)
    patronymic = models.CharField(blank=True, max_length=20)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Author.
        """
        return f"id: {self.pk} --- {self.name} {self.surname} {self.patronymic} ---"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Author object.
        """
        return f"Author(id={self.pk})"

    @staticmethod
    def get_by_id(author_id):
        """
        :param author_id: SERIAL: the id of a Author to be found in the DB
        :return: author object or None if a user with such ID does not exist
        """
        try:
            return Author.objects.get(pk=author_id)
        except Author.DoesNotExist:
            return None

    @staticmethod
    def delete_by_id(author_id):
        """
        :param author_id: an id of a author to be deleted
        :type author_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        try:
            author = Author.objects.get(pk=author_id)
            author.delete()
            return True
        except Author.DoesNotExist:
            return False

    @staticmethod
    def create(name, surname, patronymic):
        """
        """
        if (
            name
            and len(name) <= 20
            and surname
            and len(surname) <= 20
            and patronymic
            and len(patronymic) <= 20
        ):
            author = Author(name=name, surname=surname, patronymic=patronymic)
            author.save()
            return author

    def to_dict(self):
        """
        :return: author id, author name, author surname, author patronymic

        """
        return self.__dict__()

    def update(self, name=None, surname=None, patronymic=None):
        """
        Updates author in the database with the specified parameters.
        """

        if name and len(name) <= 20:
            self.name = name
        if surname and len(surname) <= 20:
            self.surname = surname
        if patronymic and len(patronymic) <= 20:
            self.patronymic = patronymic
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all authors
        """
        return Author.objects.all()

library/author/forms.py
from django import forms
from .models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["name", "surname", "patronymic"]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'patronymic': forms.TextInput(attrs={'class': 'form-control'}),
        }

library/author/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Author
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from book.models import Book
from .forms import AuthorForm


class AuthorPage(ListView):
    template_name = "author/author.html"
    model = Author
    context_object_name = "authors"
    ordering = "surname"


class AuthorDetails(DetailView):
    template_name = "author/author_details.html"
    context_object_name = "author"
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        context["books"] = Book.objects.filter(authors=author)
        return context


def remove_author(request, author_id):
    if request.method == "POST":
        try:
            author = Author.objects.get(pk=author_id)
            books_authors = Book.objects.filter(authors=author)
        except Author.DoesNotExist:
            raise Http404("Question does not exist")
        if len(books_authors) == 0:
            author.delete()
        return HttpResponseRedirect(reverse("author:author"))


def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("author:author"))
    else:
        form = AuthorForm()
    return render(request, "author/author_create.html", {"form": form})

library/author/templates/author/author.html
{% extends 'base.html' %}
{% block title %}Authors{% endblock %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Author</title>
</head>
<body>
    <div class="p-3 --bs-info-text-emphasis">
<h2>Authors:</h2>
<div class="mb-3">
    <form action="{% url 'author:add_author' %}">
        <button type="submit" class="btn btn-success">Add Author</button>
    </form>
    </div>
<div class="mb-3">
<ul class="list-group list-group-flush">
{% for author in authors %}
    <li class="list-group-item">{{ author.surname }} {{ author.name }} {{ author.patronymic }} -
        <a href="{% url 'author:details' author.id %}"> Details </a></li>
{% empty %}
    <li>No authors yet.</li>
{% endfor %}
</ul>
</div>
</div>
</body>
</html>
{% endblock %}

library/author/templates/author/author_create.html
{% extends 'base.html' %}
{% block title %}Create author{% endblock %}
{% block content %}
<body>
  <div class="p-3 --bs-info-text-emphasis">
  <h3>Add Author</h3>
  <form method="POST">
    {% csrf_token %}{{ form.non_field_errors }}
    <div class="mb-2">
      <label class="col-form-label">Name</label>
      <div class="d-flex">
        <div class="col-sm-3">{{form.name}} {{form.name.errors}}</div>
      </div>
    </div>
    <div class="mb-2">
      <label class="col-form-label">Surname</label>
      <div class="d-flex">
        <div class="col-sm-3">{{form.surname}} {{form.surname.errors}}</div>
      </div>
    </div>
    <div class="mb-2">
      <label class="col-form-label">Patronymic</label>
      <div class="d-flex">
        <div class="col-sm-3">{{form.patronymic}} {{form.patronymic.errors}}</div>
      </div>
    </div>


    <div class="mb-2">
    <button type="submit" class="btn btn-success">Submit</button>
    </div>

  </form>
  </div>
</body>
</html>
{% endblock %}

library/author/templates/author/author_details.html
{% extends 'base.html' %}
{% block title %}Author_details{% endblock %}
{% block content %}
<body>
    <div class="p-3 --bs-info-text-emphasis ">
<h3>Information about {{author.surname}} {{author.name}} {{author.patronymic}} books:</h1>
    {% for book in books %}
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Title:</strong> {{book.name}}  </li>
        <li class="list-group-item"><strong>Description:</strong> {{book.description}}</li>
        <li class="list-group-item"></li>
    </ul>
        {% empty %}
        <div class="mb-3">
        No books yet.
        </div>
        <form action="{% url 'author:remove_author' author.id %}" method="post">
            {% csrf_token %}
        <div class="mb-3">
            <button type="submit" class="btn btn-success">Remove author</button>
        </div>
        </form>
    {% endfor %}
</div>
</body>
</html>
{% endblock %}